export const ErrorTypes = {
  SERVER_ERROR: 'SERVER_ERROR',
  CLIENT_ERROR: 'CLIENT_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOTFOUND: 'NOTFOUND',
  UNKNOWN_ERROR: 'UNAUTHORIZED',
  CONNECTION_ERROR: 'CONNECTION_ERROR',  // axios无法链接到服务端
};
