active-environment: global
application:
  dev-mode: true
  information:
    name: musicatri
    version: 1.0.0
    description: neo-musicatri
  logging:
    print-banner: true  # 打印musicatri旗帜
    default-logging:  # 默认日志
      enable: true
      level: DEBUG
    console-logging:  # 控制台日志
      enable: true
      level: DEBUG
    filelog-logging:  # 文件日志
      enable: true
      level: DEBUG
      extname: api
      file-directory: logs  # temp/logs
  security:
    secret-key: musicatri
    oauth:
      insecure-transport: false  # 允许在HTTP下执行oauth
      relax-token-scope: True  # 允许动态调整oauth申请权限
    cors:
      allow-origins: [http://localhost:5173, http://localhost:5174]
      allow_headers: [Content-Type, Authorization, Accept-Language]
      allow-methods: [GET, POST, PUT, DELETE, TRACE]
      supports-credentials: true
  wsgi-server:
    host: 0.0.0.0
    port: 5001
    werkzeug:
      debug-mode: false
      log-output: false
      use-reloader: false
  nacos:
    server-addr: localhost
    server-port: 8848
    registration:
      service-name: server-bot
      service-addr: localhost
      service-port: 5000
      heartbeat-interval: 10
  swagger:
    title: server-bot API接口文档
    uiversion: 3
    description: 机器人服务API接口文档
    version: 0.1.0
    terms-of-service: https://blu3evil.github.io/musicatri1
    contact:
      name: pineclone
      email: pineclone@outlook.com
      url: https://github.com/eyespore
    license:
      name: MIT
      url: https://opensource.org/licenses/MIT
---
environment: docker  # dev
application:
  session:
    redis:
      host: 172.17.208.1
      port: 6379
  cache:
    redis:
      host: 172.17.208.1
      port: 6379
  database:
    host: 172.17.208.1
    port: 3306
